### PR TITLE
Finished UCSBOrganizations Fixtures

### PR DESCRIPTION
**Pull request by EduinoMEH**
This closes Issue #18, no testing was needed, just needed to be similar to the JSON format that's returned from `GET` endpoint.

### CODE REVIEW

**Review by vedp3705 — CHANGES_REQUESTED** [review]
Run npm run format to fix the 35-frontend-format error.

**Comment by EduinoMEH** [comment]
> Run npm run format to fix the 35-frontend-format error.

I just performed the formatting, and all checks are good (including Chromatic).

**Review by vedp3705 — APPROVED** [review]
LGTM!

**Review by rushil-x-gupta — APPROVED** [review]
Looks good!

**Pull request merged**
