### PR TITLE
Created Menu Item Fixtures and Form

### PR DESCRIPTION
**Pull request by leozhu0**
Completed Menu Item fixtures and form. This includes the tests for the form as well as the stories. The link to the chromatic story book is as follows: https://6726c65fac869bba81d3d68d-nrritlonyp.chromatic.com/

Below is a sample image of the form.
Screenshot 2024-11-06 at 2 42 40 PM

### CODE REVIEW

**Review by EduinoMEH — APPROVED** [review]
Looks good to me! Nice job :D.

**Review by berdly — COMMENTED** [review]
Everything looks good except I'm wondering why there are changes in frontend/public/mockServiceWorker.js. I don't think we're supposed to edit that, and anyway the changes like removing semicolons and such seem more error prone.

**Comment by leozhu0** [comment]
> Everything looks good except I'm wondering why there are changes in frontend/public/mockServiceWorker.js. I don't think we're supposed to edit that, and anyway the changes like removing semicolons and such seem more error prone.

I actually have no idea how that happened. Im assuming it was npm run format that changed that because I don't even remember opening that file. What do you recommend I do?

**Comment by leozhu0** [comment]
> > Everything looks good except I'm wondering why there are changes in frontend/public/mockServiceWorker.js. I don't think we're supposed to edit that, and anyway the changes like removing semicolons and such seem more error prone.
> 
> I actually have no idea how that happened. Im assuming it was npm run format that changed that because I don't even remember opening that file. What do you recommend I do?

I've fixed this issue by replacing it with the nonmodified version from main.

**Review by berdly — APPROVED** [review]
okay yeah, looks good now!

**Pull request merged**
