### PR TITLE
Leozhu0 UCSB Dining Commons Menu Items Table

### PR DESCRIPTION
**Pull request by leozhu0**
Completed all parts of the UCSB Dining Commons Menu Items Table including tests and stories. The Chromatic storybook is as follows: https://6726c65fac869bba81d3d68d-nzbfotqjll.chromatic.com/

Screenshot 2024-11-07 at 3 27 17 PM

### CODE REVIEW

**Review by EduinoMEH — APPROVED** [review]
Looks good to me!

**Review by berdly — COMMENTED** [review]
Same issue with the mock service worker file

**Comment by leozhu0** [comment]
All issues have been resolved. Please review and merge as soon as possible.

**Review by billybobjoe123 — APPROVED** [review]
looks good

**Pull request merged**
